table financials
	lineageTag: 190b4925-d2f6-452c-8050-37dcba5ab1ec

	column Segment
		dataType: string
		lineageTag: 4fc3ee3f-b2f4-4f5e-8c02-929b65240aa7
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 95d9f69a-41ee-4d99-9d8f-0ba063bd2009
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: cc0c52ba-30c1-44b0-bc77-9a9333390de3
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 31ae3a57-52d4-4b98-bc9e-7f834678ec31
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: 9a196956-617f-4d51-849a-9b1924c4e714
		summarizeBy: none
		sourceColumn: Units Sold

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 8203b1a6-bc2e-44cf-bba6-19ca13d151e8
		summarizeBy: none
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = User

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 98bc1c23-25c9-465b-be25-45352142b01f
		summarizeBy: none
		sourceColumn: Sale Price

		annotation SummarizationSetBy = User

	column 'Gross Sales'
		dataType: double
		lineageTag: 4444fafe-becc-4659-aa58-cb0b010024bc
		summarizeBy: none
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 1b3e7351-0401-4e27-99f6-f40ddac7a6c9
		summarizeBy: none
		sourceColumn: Discounts

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 4f42d3b7-c8b5-4ad8-9618-a5acba639bb8
		summarizeBy: none
		sourceColumn: Sales

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: f9c8fb80-ee2e-47ec-868e-0319ba0f76f8
		summarizeBy: none
		sourceColumn: COGS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 45012542-ab94-4154-9e4e-1786b46a516c
		summarizeBy: none
		sourceColumn: Profit

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 120f0074-3e1d-4d8e-b174-04b5fb05a787
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: ac20f063-e1cb-4bb2-b792-34a98820f243
			defaultHierarchy: LocalDateTable_412d8c80-8ad5-4539-9b9e-6a504f194ba1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 45dd54df-e852-4946-9f07-5cb128a81ad9
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: cfd49b57-31d9-431a-99f2-4f04c86a068b
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1a2d5286-a1db-4a2d-8c75-d39f44445442
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\Microsoft Power BI Desktop\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

